### ISSUE TITLE
media-sound/cozy-1.2.1::nest: Error on launch packaging.version.InvalidVersion: Invalid version: 'None'

### ISSUE THREAD

**Issue by F3llFr0mTh3Sky** [SpiderX/portage-overlay#156]
I installed media-sound/cozy-1.2.1::nest which worked well, but then when I tried to start it failed to start and returned this error:
```
calico@tux ~ $ 
cozy
['/usr/bin/cozy']
15:52:20 [MainThread  ] [applicatio] [INFO ]  ('gentoo', '2.15', 'n/a')
15:52:20 [MainThread  ] [applicatio] [INFO ]  Starting up cozy 1.2.1
15:52:20 [MainThread  ] [db        ] [INFO ]  SQLite version: 3.46.0
15:52:20 [Thread-1 (ru] [peewee.sql] [INFO ]  writer received shutdown request, exiting.
15:52:20 [MainThread  ] [applicatio] [INFO ]  libhandy version: 1
handle exception
Traceback (most recent call last):
  File "/usr/lib/python3.12/site-packages/cozy/application.py", line 99, in do_activate
    self.app_controller = AppController(self, main_window_builder, self.ui)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/cozy/architecture/singleton.py", line 5, in __call__
    cls._instances[cls] = super(Singleton, cls).__call__(*args, **kwargs)
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/cozy/app_controller.py", line 52, in __init__
    self.whats_new_window: WhatsNewWindow = WhatsNewWindow()
                                            ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/cozy/ui/widgets/whats_new_window.py", line 36, in __init__
    self._fill_window()
  File "/usr/lib/python3.12/site-packages/cozy/ui/widgets/whats_new_window.py", line 54, in _fill_window
    last_launched_version = version.parse(self.app_settings.last_launched_version)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/packaging/version.py", line 56, in parse
    return Version(version)
           ^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/site-packages/packaging/version.py", line 202, in __init__
    raise InvalidVersion(f"Invalid version: '{version}'")
packaging.version.InvalidVersion: Invalid version: 'None'

```
The issue might be caused by the ebuild, otherwise updating it to 1.3.0 might fix the issue.

**Comment by SpiderX** [comment]
@F3llFr0mTh3Sky When you merge this ebuild for the first time it will output the [following](https://github.com/SpiderX/portage-overlay/blob/master/media-sound/cozy/cozy-1.2.1.ebuild#L42) message:

> The following must be executed after install:
> gsettings set com.github.geigi.cozy last-launched-version '1.2.1'

This commands fix issue you have mentiond. More into [here](https://github.com/geigi/cozy/issues/756).

New version [pushed](e2179b3bd1f8ed6dd4c47809cee22c9865d39a9b).
